[theme]
base="dark"
backgroundColor="#11254c"
secondaryBackgroundColor="#1f202d"


# ---- Brand colors ----
primaryColor = "#251db8ff"          # Indigo accent for buttons/sliders
backgroundColor = "#0E1117"       # Deep gray background
secondaryBackgroundColor = "#1B1F27"  # Card/sidebar background
textColor = "#EDEDED"             # Soft white text

# ---- Typography ----
font = "sans serif"               # clean UI font